export const SET_WAS_INIT = 'SET_WAS_INIT';
export const SET_ALL_PAGES_IDS = 'SET_ALL_PAGES_IDS';
export const SET_SELECTED_PAGE_ID = 'SET_SELECTED_PAGE_ID';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_OPEN_IDS = 'SET_OPEN_IDS';
export const SET_TREE_OPEN_IDS = 'SET_TREE_OPEN_IDS';
export const SET_SELECTED_ANCHOR_ID = 'SET_SELECTED_ANCHOR_ID';